name: Deploy API to Render

on:
  push:
    branches: [ main ]   # cambia si usas otra rama
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Setup Node.js
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      # Instalar dependencias
      - name: Install dependencies
        run: npm ci

      # (Opcional) Ejecutar lint/test
      - name: Lint/Test (optional)
        run: |
          npm run lint --if-present
          npm test --if-present

      # Desencadenar despliegue en Render
      - name: Trigger Render Deploy Hook
        run: |
          curl -fsSL -X POST "https://api.render.com/deploy/srv-d3rhse6r433s73e5m3ag?key=u3SprO83V4I"
